const chapters = [
  {
    background: '#e2e2e2',
    color: 'black',
    image: 'images/1_Later-Date.png',
    image_cue: [23, 48.909],
    audio: 'audio/1_Later-Date.mp3',
    transcript: [
      [0.1, 'Click.', true],
      [0.9, '', true],
      [1.670, 'Voice like a recording.', true],
      [1.670, 'Encased in a white chat box with black monotype text is a statement'],
      [8.276, '“I think one day we will be able to go outside again.”'],
      [14.633, '', true],
      [14.633, 'A down arrow follows the statement, prompting the user to expand the context of the conversation.'],
      [22.19, ''],
      [22.19, '', true],
      [24, 'Low tonal sounds.', true],
      [26.231, 'As we waited in the middle of everything last March,'],
      [26.231, 'A different voice.', true],
      [28, 'I kept thinking about how “later” had taken on new importance.'],
      [32.430, 'It had been elevated from that place to which'],
      [34.000, 'we’d relegate anything that did not really concern us'],
      [32.430, 'Deep rumbling.', true],
      [37.004, 'to a place where we’d do everything.'],
      [38.884, 'I built a web interface to facilitate a series of online chats with people'],
      [43, '', true],
      [44.305, 'where we would make plans for a “later date”'],
      [46.862, 'when we were able to go outside again.'],
      [48.909, 'I fantasized about these later dates.'],
      [51, 'Sounds of outside, birds, people talking.', true],
      [52, 'Being in the same space as other people.'],
      [53.661, 'Reaching out and touching.'],
      [55.791, 'Shared surfaces.'],
      [57.381, 'Breathing, talking, anything really.'],
      [58, 'Rustling. Inhaling. Typing.', true],
      [59.819, 'It is a performance in two parts.'],
      [61, '', true],
      [62.670, 'In the first, we chat and imagine together our first meeting.'],
      [66.970, 'Where will we go, what will we do, what will we say?'],
      [70.960, 'This future plan gets saved as a sort of script.'],
      [73.850, 'Later, when allowed out again, they receive a request to meet and we enact this script.'],
      [76, 'Dogs barking, wind blowing.', true],
      [80.380, 'This is part two.'],
      [82, 'People laughing outside.', true],
      [84.530, 'You were one of the last people I saw before the UCLA campus closed down that day.'],
      [84.530, '', true],
      [86, 'People talking.', true],
      [90, 'Small objects being rearranged on a table.', true],
      [91.149, 'We were having grad reviews.'],
      [93.427, 'We sat on a couch together looking at'],
      [94, 'High frequency vibrations.', true],
      [96.103, 'jittery data visualization I made using flight data.'],
      [100.528, 'Would it be that jittery if I took data just a few weeks later?'],
      [100.644, 'Sliding papers, equipment clicking.', true],
      [105, 'Everything in the room was dark, minus the projection light.'],
      [110, 'Beep.', true],
      [111, '', true],
      [111.000, 'The furniture was shifted around to accommodate my install.'],
      [113, 'Whir of projector fan.', true],
      [115.596, 'Changes to a familiar space seemed to add dramatic effect to what was going on outside the school walls.'],
      [120, 'Voice distorted, panning around.', true],
      [123.433, 'The future was looming in the air.'],
      [123.433, 'Hollow metallic tone.', true],
      [125.700, 'We both wondered what would happen.'],
      [127.600, 'Or if anything would happen at all. '],
      [127.600, 'Shifting in seat.', true],
      [131, '', true],
      [131.077, 'How would the events that were to unfold going to change our lives?'],
      [136, 'Frantic typing.', true],
      [138.500, '', true],
      [138.500, 'We were planning with each other while we were negotiating with the future.'],
      [142.220, 'What season will it be?'],
      [144.159, 'Will we be able to embrace?'],
      [146.239, 'Will that place still exist?'],
      [148.180, 'We talked about the first days when frantic decisions were being made,'],
      [149, 'People anxiously talking.', true],
      [151.377, 'and each of our personal boundaries closing in as we began to feel unsafe with one another.'],
      [155.900, 'We acknowledged the discomfort of trying to find a stable place in a situation we refuse to accept as normal.'],
      [162.569, 'We make extremely specific plans, subject to change.'],
      [164, 'Heavy hum.', true],
      [167.170, 'Our conversation was the opposite of a Zoom grid.'],
      [169.630, 'It was one-to-one, slow, text-only.'],
      [172.689, 'I called this piece a performance, but with the camera off,'],
      [175.867, 'it felt like the first non-performance I had experienced in weeks.'],
      [179, 'Lo-fi melancholy melody.', true],
      [179.900, 'The interaction is about waiting instead of streaming.'],
      [183.910, 'And in this lack of bandwidth, we are left space to imagine.'],
      [186.129, 'The person on the other end, whose presence we are only certain of at brief moments when messages pop onscreen.'],
      [186.129, 'Music rising, hanging thick in the air.', true],
      [193.319, 'The later with this person when we will meet in highest fidelity.'],
      [196.439, 'The days and months that will unfold after this exchange.'],
      [196.439, 'Lo-fi melancholy melody. Crackling sounds of static.', true],
      [201, ''],
      [201, 'A record left running.', true],
      [208, '', true],
    ]
  },  
  {
    background: '#32210c',
    color: 'white',
    image: 'images/2_I-Heard-Talking-Is-Dangerous.jpg',
    image_cue: [26, 50],
    audio: 'audio/2_I-Heard-Talking-Is-Dangerous.mp3',
    transcript: [
      [1.220, 'Lauren stands on a patch of grass outside a home with her back towards the camera.'],
      [6.674, 'Two young masked people stand at the top of a small set of stairs.'],
      [8, 'Low wind growing in the distance.', true],
      [11.611, 'At this distance, it is uncertain if they are looking at Lauren'],
      [15.339, 'or at the smartphone in Lauren’s left hand.'],
      [15.339, 'Rumbling.', true],
      [18.682, 'The phone is extended forward for legibility and rotated in landscape mode.'],
      [24.000, 'All three people pictured are nicely dressed.'],
      [26, ''],
      [24, '', true],
      [27, 'A wave of cars driving by. A voice like Siri.', true],
      [28.892, 'It is important to be kind during stressful times.'],
      [34, 'Hum of machines in an empty room.', true],
      [34.343, 'It\'s hard to hold all these different contexts in mind.'],
      [40, 'Cars sliding by like water. Almost like being at a beach.', true],
      [38.460, 'Anybody that can live in solitude is a powerful being.'],
      [44.512, 'At a crowded supermarket, the panic was palpable.'],
      [47.5, 'Clicking of a gas stove.', true],
      [49, '', true],
      [50, ''],
      [50.399, 'This was the first in a series of gestures over the past year trying to deal with the'],
      [54.700, 'profound isolation I felt, stuck behind screens,'],
      [56, 'Low whistle beneath the surface.', true],
      [57.931, 'backgrounded by a pervasive fear, suspended in time.'],
      [61.670, 'I think most of us were feeling it.'],
      [64.067, 'With the murder of George Floyd, that anxiety exploded into rage and grief that took over the streets,'],
      [66, 'People shouting in the distance. Police burps.', true],
      [69.115, 'simultaneously bringing us together and pushing us further apart.'],
      [73.345, 'Our understanding of who is trustworthy, what is safe to do and talk about shifted.'],
      [75, 'Louder chanting. Police shouting.', true],
      [78.030, 'While the medical advice continued to evolve and update.'],
      [83, 'Kettle rising and rising.', true],
      [81.190, 'Avoid surfaces.'],
      [82.190, 'Check in with your friends.'],
      [83.820, 'Don’t wear masks.'],
      [84.979, 'Wear two.'],
      [85.979, 'Don’t call, give them space.'],
      [87.670, 'Keep six feet.'],
      [88, 'Rising.', true],
      [88.722, 'Protest the right things.'],
      [90.024, 'Don’t fly.'],
      [91.159, 'Don’t talk politics.'],
      [92.627, 'Restaurants are open,'],
      [93.894, 'Schools are unsafe.'],
      [96.162, 'Feeling completely disconnected, I created I heard TALKING IS DANGEROUS'],
      [97, 'Whistle resigns.', true],
      [100.353, 'trying to break through.'],
      [101, '', true],
      [102.390, 'Showing up on doorsteps, I deliver a monologue via phone screen and text-to-speech.'],
      [106.592, 'I explain that I just heard masks and six feet are not safe enough.'],
      [111.100, 'Because when you speak, tiny particles fly out through your mask at high velocity.'],
      [112, 'Quiet street sounds.', true],
      [115.200, 'They’ve recommended we stop talking to each other.'],
      [118, 'Beeping.', true],
      [118.135, 'They say talking is dangerous.'],
      [120.397, 'So I made an alternative.'],
      [122.370, 'I invite each person to visit a URL on their phone to continue the conversation.'],
      [124, 'Empty space.', true],
      [127.810, 'We proceed, discussing danger, safety, the future.'],
      [127.810, '', true],
      [132.280, 'Over the months we have learned to say things via text that perhaps'],
      [135.227, 'we couldn\'t in a more embodied way.'],
      [137.890, 'Could this form of typing-speaking open anything for us?'],
      [140, 'Cars driving, street noise.', true],
      [145.760, 'Siri again.',true],
      [145.760, 'Sometimes I feel like listening is more dangerous than talking.'],
      [150.050, 'Is there really safety in distance?'],
      [154.630, 'Can we understand each other without talking?'],
      [159.658, 'A satisfying human voice.', true],
      [159.658, 'Ah, I remember how short I am again.'],
      [163.880, '', true],
      [163.880, 'I completely forgot what your lower body looked like.'],
      [168.191, 'I never thought I needed to remember..'],
      [172.112, 'Sorry, I can’t read that fast.'],
      [175.926, 'Can you bring the phone a little closer?'],
      [177, 'Beeping in the distance.', true],
      [179.315, 'Is the audio up all the way?'],
      [183.434, '', true],
      [183.434, 'I keep wondering, in moments before laughter,'],
      [187.321, 'when our gut is about to push out air from our mouths with a force greater than speaking,'],
      [193.242, 'How will we compose ourselves then?'],
      [196, 'The noise of an empty street at night.', true],
      [201.940, 'Siri voice.', true],
      [201.940, 'I care about you immensely.'],
      [204, ''],
      [205, '', true]
    ]
  },
  {
    background: '#ff1e00',
    color: 'white',
    image: false,
    audio: 'audio/3_You-Can-Say.mp3',
    transcript: [
      [0, 'Zoom doorbell.', true],
      [0, '[FLASH]'],
      [0.410, 'When I became exhausted with the constant Zoom calls,'],
      [0.6, '', true],
      [1.0, 'Zoom doorbell.', true],
      [1.0, '[FLASH]'],
      [1.8, 'Zoom doorbell. Zoom doorbell. Zoom doorbe...', true],
      [1.8, '[FLASH]'],
      [2.2, '[FLASH]'],
      [2.8, '[FLASH]'],
      [3.2, '[FLASH]'],
      [3.300, 'I created a digital clone of my voice to replace me.'],
      [5, '[FLASH]'],
      [6, 'Typing.', true],
      [6.985, 'This voice allows me to puppet myself, '],
      [9.427, '', true],
      [9.427, 'using it to say all the things I hadn\'t previously been able to vocalize.'],
      [14.340, 'Distorted, synthesized voices.', true],
      [14.340, 'I play with the phrases we expect from one another, and from machines.'],
      [18, '', true],
      [18, 'You can say “Turn off the lights.”'],
      [20.8, 'You can say “Wake me up at 7am.”'],
      [23.8, 'You can say “Talk to me.”'],
      [26.290, 'Double tone.', true],
      [27.690, 'I am captivated by the ways we are taught to interact with algorithms,'],
      [27.690, 'Clicks.', true],
      [30, 'Percussive tones.', true],
      [31.088, 'and how this shapes the way we interact with each other.'],
      [31, 'Sorry, I didn\'t get that.', true],
      [32.5, '', true],
      [33.880, 'What are the rules, what happens when we introduce glitches?'],
      [34, 'Clicks. Tones. Typing.', true],
      [36.5, 'Sorry, I didn\'t get that.', true],
      [38, '', true],
      [37.715, 'I feel a sense of power owning the data of my own voice.'],
      [41.768, 'I am taking it back from the tech companies, constantly tapping my conversations,'],
      [42.5, 'Growing low drone.', true],
      [45.797, 'sampling and analyzing and archiving my speech for future use yet unknown.'],
      [45, '[HA]', 130],
      [45, 'Ha haha ha...', true],
      [47, 'Hahahaahahahhh hahaahhaaha...', true],
      [51.120, 'Instead, I offer the control of my voice to others.'],
      [52, 'Hahahahahhaaahhhhhaah hahahaa...', true],
      [54.539, 'Upon visiting my website, each visitor is asked by my voice,'],
      [58.980, 'Synthesized voice.', true],
      [58.980, '“What do you want me to say?”'],
      [61.113, '', true],
      [61.113, 'However they reply, my voice responds by speaking their own words back to them.'],
      [65.810, 'Then it asks again, “What do you want me to say?”'],
      [67.5, 'Synthesized voice.', true],
      [69.320, 'Spacious drone.', true],
      [69.320, 'I feel so abhorrent.'],
      [71.380, 'I feel so absorbed.'],
      [72, 'Light notes dissolving.', true],
      [72.863, 'I feel so accepting.'],
      [74.400, 'I feel so aching.'],
      [75, 'Synthesized voice.', true],
      [75.830, 'I feel so admiring.'],
      [77.500, 'You can say “What time is it?”'],
      [79.343, 'You can say “What day is it?”'],
      [81.186, 'You can say “What am I doing tomorrow?”'],
      [83, ''],
      [83, 'Drone rumble. Typing or a mouse crawling through tunnels.', true],
    ]
  },
  {
    background: '#091116',
    color: 'white',
    image: 'images/4_Sleepover.jpg',
    image_cue: [26, 63],
    audio: 'audio/4_Sleepover.mp3',
    transcript: [
      [0.520, 'In the foreground, a silhouette of shrubs frame Lauren in the midground.'],
      [1.5, 'Cicadas.', true],
      [5.870, 'She lays in a sleeping bag in her friend’s backyard.'],
      [10.270, 'Her form is disguised into the surrounding darkness'],
      [11.2, 'Shifting body.', true],
      [13.676, 'apart from the light from her smartphone screen illuminating her face.'],
      [15, 'Car driving.', true],
      [18.860, 'An overhead light also shows traces of outdoor furniture behind her'],
      [20.5, 'Low vibration. Cicadas grow louder.', true],
      [24.674, 'and the fences that reveal the boundary of the backyard.'],
      [26, ''],
      [29, 'Car slides by.', true],
      [32, '', true],
      [34.440, 'The further I got into this series of voice experiments, the more I began to dissociate.'],
      [39.630, 'It became hard to tell what existed beyond my computer screen.'],
      [41, 'Distant tones. A computer booting.', true],
      [43.550, 'Months of caution began to induce feelings of extreme recklessness and futility.'],
      [49, 'Hollow chimes.', true],
      [48.280, 'In a last ditch effort to get close, I sent text messages to friends.'],
      [52.767, 'A holiday offering of my live body outside their home.'],
      [54, 'Rythmic pulses, characters in a message box.', true],
      [56.390, 'We have only text communication.'],
      [58.517, 'I spend the night out on their lawn.'],
      [60, 'Sending slurp.', true],
      [60.570, 'Each of us thinking of the other’s physicality.'],
      [61, '', true],
      [61.5, ''],
      [63.1, 'Seeking presence.'],
      [63.1, 'Door opens.', true],
      [65, 'Chimes.', true],
      [68.679, 'Suddenly, my motion sensor lights turned off.'],
      [68.679, 'Cicadas, crickets.', true],
      [71.757, 'And your whole body disappeared into the night.'],
      [71.757, '', true],
      [75.530, 'Aside from your face which was illuminated by your phone that you held above you.'],
      [80, 'Phone screen locking.', true],
      [81, '', true],
      [82.275, 'Slightly uneased and amused, I messaged you,'],
      [86, 'Sending slurp.', true],
      [86.293, 'And I said, “I left the back door unlocked in case you need to use the restroom tonight.”'],
      [87, '', true],
      [92.779, 'And the typing bubble appeared and I looked to see your fingers move across your screen in that instance.'],
      [95, 'Typing like wet drops.', true],
      [98.858, '“Thanks!” you reply.'],
      [100, ''],
      [104.469, 'I feel safety in this closeness at distance.'],
      [104.469, '', true],
      [107.220, 'While I’m thinking of all the others outside every night in more precarious positions.'],
      [111.909, 'Last spring, we witnessed extraordinary measures taken to provide housing and care.'],
      [113, 'Material zipping. Shifting.', true],
      [117.197, 'Measures we were previously told were too hard and too expensive and would take too much time.'],
      [122.845, 'As these safety nets are now being unravelled, how do we keep demanding support for the most vulnerable?'],
      [125, 'Echoing empty noise.', true],
      [128.910, 'Who are the people outside our homes that we choose to think of at night?'],
      [130.5, ''],
      [132, '', true],
    ]
  },
  {
    background: 'black',
    color: '#717171',
    image: false,
    audio: 'audio/5_Good-Night.mp3',
    transcript: [
      [0, 'Loud vibrating tone.', true],
      [2.340, 'After a year spent fearing for our health, grieving the loss of loved ones,'],
      [6.610, '', true],
      [6.610, 'watching the ever growing death counts,'],
      [8.951, 'I have never felt so in touch with my own mortality.'],
      [8.951, 'Static rumbling.', true],
      [11.990, 'Drifting confused between utter stagnation and overwhelming transience,'],
      [13, 'Drone moving through empty space.', true],
      [15.914, 'I started Good Night.'],
      [17.5, 'A drop.', true],
      [18.416, '', true],
      [18.416, 'A performance for one person that continues as long as I am alive.'],
      [21, 'Button drips.', true],
      [23.548, 'Every night before sleep, I text the owner of the work “good night.”'],
      [28.145, 'At any point, that person may choose to pass the work to someone else,'],
      [30, 'Sending slurp.', true],
      [31, '', true],
      [32.424, 'at which point the good night texts transfer to the next person.'],
      [37.612, 'It is the first in a series of rest of life performances I plan to complete.'],
      [42.684, 'What does it mean to commit, to something or someone,'],
      [44, 'Button taps.', true],
      [45.684, 'when the end is so palpable yet unknown?'],
      [48.5, 'Sending slurp.', true],
      [49.5, '', true],
      [49.816, 'This series of pandemic works are about'],
      [51.768, 'isolation, breakdown, danger, disconnection, grief, frustration, communication, wanting.'],
      [61.809, 'Streaming ourselves through every possible channel, platform, and app,'],
      // [64, 'High tap tap tap.', true],
      [66.275, 'how do we hold the bits of each other together?'],
      // [69, 'Slurp.', true],
      // [69.5, '', true],
      [72, '']
    ]
  },

];

