const chapters = [
  {
    background: '#e2e2e2',
    color: 'black',
    image: 'images/1_Later-Date.png',
    image_cue: [23, 48],
    audio: 'audio/1_Later-Date.mp3',
    transcript: [
      [1, 'Encased in a white chat box with black monotype text is a statement'],
      [8, '“I think one day we will be able to go outside again.”'],
      [15, 'A down arrow follows the statement, prompting the user to expand the context of the conversation.'],
      [18, 'Low tonal sounds.', true],
      [22.19, ''],
      [22.19, '', true],
      [26, 'As we waited in the middle of everything last March,'],
      [28, 'I kept thinking about how “later” had taken on new importance.'],
      [32, 'It had been elevated from that place to which we’d relegate anything that did not really concern us'],
      [32, 'Deep rumbling.', true],
      [37, 'to a place where we’d do everything.'],
      [39, 'I built a web interface to facilitate a series of online chats with people'],
      [43, '', true],
      [44, 'where we would make plans for a “later date”, when we were able to go outside again.'],
      [48, 'I fantasized about these later dates.'],
      [51, 'Sounds of outside, birds, people talking.', true],
      [52, 'Being in the same space as other people.'],
      [54, 'Reaching out and touching.'],
      [55, 'Shared surfaces.'],
      [57, 'Breathing, talking, anything really.'],
      [51, 'Rustling. Inhaling. Typing.', true],
      [60, 'It is a performance in two parts.'],
      [61, '', true],
      [62, 'In the first, we chat and imagine together our first meeting.'],
      [66, 'Where will we go, what will we do, what will we say?'],
      [70, 'This future plan gets saved as a sort of script.'],
      [73, 'Later, when allowed out again, they receive a request to meet and we enact this script.'],
      [76, 'Dogs barking, wind blowing.', true],
      [80, 'This is part two.'],
      [76, 'People laughing outside.', true],
      [84, 'You were one of the last people I saw before the UCLA campus closed down that day.'],
      [84, '', true],
      [86, 'People talking.', true],
      [90, 'People talking. Small objects being rearranged on a table.', true],
      [91, 'We were having grad reviews.'],
      [93, 'We sat on a couch together looking at a jittery data visualization I made using flight data.'],
      [95, '', true],
      [100, 'Would it be that jittery if I took data just a few weeks later?'],
      [100, 'Sound of sliding papers, creaking chair.', true],
      [105, 'Everything in the room was dark, minus the projection light.'],
      [110, 'Beep.', true],
      [111, '', true],
      [111, 'The furniture was shifted around to accommodate my install.'],
      [113, 'Whir of projector fan.', true],
      [115, 'Changes to a familiar space seemed to add dramatic effect to what was going on outside the school walls.'],
      [120, 'Voice distorted, panning around.', true],
      [123, 'The future was looming in the air.'],
      [123, 'Hollow metallic tone.', true],
      [125, 'We both wondered what would happen.'],
      [127, 'Or if anything would happen at all. '],
      [127, 'Shifting in seat.', true],
      [131, '', true],
      [131, 'How would the events that were to unfold going to change our lives?'],
      [136, 'Frantic typing.', true],
      [138, '', true],
      [138, 'We were planning with each other while we were negotiating with the future.'],
      [142, 'What season will it be?'],
      [144, 'Will we be able to embrace?'],
      [146, 'Will that place still exist?'],
      [148, 'We talked about the first days when frantic decisions were being made,'],
      [148, 'People anxiously talking.', true],
      [151, 'and each of our personal boundaries closing in as we began to feel unsafe with one another.'],
      [155, 'We acknowledged the discomfort of trying to find a stable place in a situation we refuse to accept as normal.'],
      [157, 'Foreboding hum.', true],
      [162, 'We make extremely specific plans, subject to change.'],
      [167, 'Our conversation was the opposite of a Zoom grid.'],
      [169, 'It was one-to-one, slow, text-only.'],
      [172, 'I called this piece a performance, but with the camera off, it felt like the first non-performance I had experienced in weeks.'],
      [155, 'We acknowledged the discomfort of trying to find a stable place in a situation we refuse to accept as normal.'],
      [179, 'Lo-fi melancholy melody.', true],
      [179, 'The interaction is about waiting instead of streaming.'],
      [183, 'And in this lack of bandwidth, we are left space to imagine.'],
      [186, 'The person on the other end, whose presence we are only certain of at brief moments when messages pop onscreen.'],
      [193, 'The later with this person when we will meet in highest fidelity.'],
      [196, 'The days and months that will unfold after this exchange.'],
      [196, 'Lo-fi melancholy melody. Sounds of static.', true],
      [201, ''],
      [201, 'A record left running after the music has stopped.', true],
      [208, '', true],
    ]
  },  
  {
    background: '#32210c',
    color: 'white',
    image: 'images/2_I-Heard-Talking-Is-Dangerous.jpg',
    image_cue: [26, 50],
    audio: 'audio/2_I-Heard-Talking-Is-Dangerous.mp3',
    transcript: [
      [1, 'Lauren stands on a patch of grass outside a home with her back towards the camera.'],
      [6, 'Two young masked people stand at the top of a small set of stairs.'],
      [11, 'At this distance, it is uncertain if they are looking at Lauren'],
      [15, 'or at the smartphone in Lauren’s left hand.'],
      [18, 'The phone is extended forward for legibility and rotated in landscape mode.'],
      [24, 'All three people pictured are nicely dressed.'],
      [26, ''],
      [28, 'It is important to be kind during stressful times.'],
      [34, 'It\'s hard to hold all these different contexts in mind.'],
      [38, 'Anybody that can live in solitude is a powerful being.'],
      [44, 'At a crowded supermarket, the panic was palpable.'],
      [50, 'This was the first in a series of gestures over the past year trying to deal with the'],
      [55, 'profound isolation I felt, stuck behind screens,'],
      [58, 'backgrounded by a pervasive fear, suspended in time.'],
      [61, 'I think most of us were feeling it.'],
      [64, 'With the murder of George Floyd, that anxiety exploded into rage and grief that took over the streets,'],
      [69, 'simultaneously bringing us together and pushing us further apart.'],
      [73, 'Our understanding of who is trustworthy, what is safe to do and talk about shifted.'],
      [78, 'While the medical advice continued to evolve and update.'],
      [81, 'Avoid surfaces.'],
      [82, 'Check in with your friends.'],
      [84, 'Don’t wear masks.'],
      [85, 'Wear two.'],
      [86, 'Don’t call, give them space.'],
      [88, 'Keep six feet.'],
      [89, 'Protest the right things.'],
      [90, 'Don’t fly.'],
      [91, 'Don’t talk politics.'],
      [92, 'Restaurants are open,'],
      [94, 'Schools are unsafe.'],
      [96, 'Feeling completely disconnected, I created I heard TALKING IS DANGEROUS'],
      [100, 'trying to break through.'],
      [102, 'Showing up on doorsteps, I deliver a monologue via phone screen and text-to-speech.'],
      [106, 'I explain that I just heard masks and six feet are not safe enough.'],
      [111, 'Because when you speak, tiny particles fly out through your mask at high velocity.'],
      [115, 'They’ve recommended we stop talking to each other.'],
      [118, 'They say talking is dangerous.'],
      [120, 'So I made an alternative.'],
      [122, 'I invite each person to visit a URL on their phone to continue the conversation.'],
      [127, 'We proceed, discussing danger, safety, the future.'],
      [132, 'Over the months we have learned to say things via text that perhaps'],
      [135, 'we couldn\'t in a more embodied way.'],
      [137, 'Could this form of typing-speaking open anything for us?'],
      [145, 'Sometimes I feel like listening is more dangerous than talking.'],
      [150, 'Is there really safety in distance?'],
      [154, 'Can we understand each other without talking?'],
      [159, 'Ah, I remember how short I am again.'],
      [163, 'I completely forgot what your lower body looked like.'],
      [168, 'I never thought I needed to remember.'],
      [172, 'Sorry, I can’t read that fast.'],
      [175, 'Can you bring the phone a little closer?'],
      [179, 'Is the audio up all the way?'],
      [183, 'I keep wondering, in moments before laughter,'],
      [187, 'when our gut is about to push out air from our mouths with a force greater than speaking,'],
      [193, 'How will we compose ourselves then?'],
      [201, 'I care about you immensely.'],
      [203, '']
    ]
  },
  {
    background: '#ff1e00',
    color: 'white',
    image: false,
    audio: 'audio/3_You-Can-Say.mp3',
    transcript: [
      [0, 'When I became exhausted with the constant Zoom calls,'],
      [3, 'I created a digital clone of my voice to replace me.'],
      [7, 'This voice allows me to puppet myself, '],
      [9, 'using it to say all the things I hadn\'t previously been able to vocalize.'],
      [14, 'I play with the phrases we expect from one another, and from machines.'],
      [19, 'You can say “Turn off the lights.”'],
      [21, 'You can say “Wake me up at 7am.”'],
      [24, 'You can say “Talk to me.”'],
      [27, 'I am captivated by the ways we are taught to interact with algorithms, [Sorry, I didn\'t get that.]'],
      [31, 'and how this shapes the way we interact with each other.'],
      [33, 'What are the rules, what happens when we introduce glitches?'],
      [37, '[Sorry, I didn\'t get that.] I feel a sense of power owning the data of my own voice.'],
      [41, 'I am taking it back from the tech companies, constantly tapping my conversations,'],
      [45, 'sampling and analyzing and archiving my speech for future use yet unknown.'],
      [51, 'Instead, I offer the control of my voice to others.'],
      [54, 'Upon visiting my website, each visitor is asked by my voice,'],
      [58, '“What do you want me to say?”'],
      [61, 'However they reply, my voice responds by speaking their own words back to them.'],
      [65, 'Then it asks again, “What do you want me to say?”'],
      [69, 'I feel so abhorrent.'],
      [71, 'I feel so absorbed.'],
      [72.5, 'I feel so accepting.'],
      [74, 'I feel so aching.'],
      [75.5, 'I feel so admiring.'],
      [77.5, 'You can say “What time is it?”'],
      [79, 'You can say “What day is it?”'],
      [81, 'You can say “What am I doing tomorrow?”'],
      [83, '']
    ]
  },
  {
    background: '#091116',
    color: 'white',
    image: 'images/4_Sleepover.jpg',
    image_cue: [26, 63.190],
    audio: 'audio/4_Sleepover.mp3',
    transcript: [
      [0.520, 'In the foreground, a silhouette of shrubs frame Lauren in the midground.'],
      [5.870, 'She lays in a sleeping bag in her friend’s backyard.'],
      [10.270, 'Her form is disguised into the surrounding darkness'],
      [13.676, 'apart from the light from her smartphone screen illuminating her face.'],
      [18.860, 'An overhead light also shows traces of outdoor furniture behind her'],
      [24.674, 'and the fences that reveal the boundary of the backyard.'],
      [26, ''],
      [34.440, 'The further I got into this series of voice experiments, the more I began to dissociate.'],
      [39.630, 'It became hard to tell what existed beyond my computer screen.'],
      [43.550, 'Months of caution began to induce feelings of extreme recklessness and futility.'],
      [48.280, 'In a last ditch effort to get close, I sent text messages to friends.'],
      [52.767, 'A holiday offering of my live body outside their home.'],
      [56.390, 'We have only text communication.'],
      [58.517, 'I spend the night out on their lawn.'],
      [60.570, 'Each of us thinking of the other’s physicality.'],
      [63.190, 'Seeking presence.'],
      [68.679, 'Suddenly, my motion sensor lights turned off.'],
      [71.757, 'And your whole body disappeared into the night.'],
      [75.530, 'Aside from your face which was illuminated by your phone that you held above you.'],
      [82.275, 'Slightly uneased and amused, I messaged you,'],
      [86.293, 'And I said, “I left the back door unlocked in case you need to use the restroom tonight.”'],
      [92.779, 'And the typing bubble appeared and I looked to see your fingers move across your screen in that instance.'],
      [98.858, '“Thanks!” you reply.'],
      [104.469, 'I feel safety in this closeness at distance.'],
      [107.220, 'While I’m thinking of all the others outside every night in more precarious positions.'],
      [111.909, 'Last spring, we witnessed extraordinary measures taken to provide housing and care.'],
      [117.197, 'Measures we were previously told were too hard and too expensive and would take too much time.'],
      [122.845, 'As these safety nets are now being unravelled, how do we keep demanding support for the most vulnerable?'],
      [128.910, 'Who are the people outside our homes that we choose to think of at night?'],
      [131, '']
    ]
  },
  {
    background: 'black',
    color: '#717171',
    image: false,
    audio: 'audio/5_Good-Night.mp3',
    transcript: [
      [2.340, 'After a year spent fearing for our health, grieving the loss of loved ones,'],
      [6.610, 'watching the ever growing death counts,'],
      [8.951, 'I have never felt so in touch with my own mortality.'],
      [11.990, 'Drifting confused between utter stagnation and overwhelming transience,'],
      [15.914, 'I started Good Night.'],
      [18.416, 'A performance for one person that continues as long as I am alive.'],
      [23.548, 'Every night before sleep, I text the owner of the work “good night.”'],
      [28.145, 'At any point, that person may choose to pass the work to someone else,'],
      [32.424, 'at which point the good night texts transfer to the next person.'],
      [37.612, 'It is the first in a series of rest-of-life performances I plan to complete.'],
      [42.684, 'What does it mean to commit, to something or someone, when the end is so palpable yet unknown?'],
      [49.816, 'This series of pandemic works are about'],
      [51.768, 'isolation, breakdown, danger, disconnection, grief, frustration, communication, wanting.'],
      [61.809, 'Streaming ourselves through every possible channel, platform, and app,'],
      [66.275, 'how do we hold the bits of each other together?'],
      [69, '']
    ]
  },

];

